server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: bank-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/hacknu_db
    username: postgres
    password: postgres
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

management:
  endpoints:
    web:
      exposure:
        include: ["health", "prometheus"]
      base-path: /actuator
  endpoint:
    health:
      show-details: always
  server.port: 8080

swagger:
  base-url: ${SWAGGER_BASE_URL:http://172.20.10.2:8080}